# Generated by Django 4.0.3 on 2022-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('intermediate', models.CharField(max_length=100)),
                ('board1', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=100)),
                ('technical_skills', models.CharField(max_length=1000)),
                ('projects', models.CharField(max_length=1000)),
                ('certifications_workshops', models.CharField(max_length=1000)),
                ('internships', models.CharField(max_length=1000)),
                ('achievements', models.CharField(max_length=1000)),
                ('strengths', models.CharField(max_length=1000)),
                ('hobbies', models.CharField(max_length=1000)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('language_known', models.CharField(max_length=100)),
                ('about_you', models.CharField(max_length=1000)),
            ],
        ),
    ]
